version: '3'
services:

  site:
    container_name: site
    image: site:latest
    restart: unless-stopped
    networks:
     - marbles
    labels:
      traefik.enable: true
      traefik.http.routers.site.entryPoints: https
      traefik.http.routers.site.rule: Host(`docs.marsblars.dev`)
    build:
      context: ./
      dockerfile: dockerfile 

  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    networks:
     - marbles
    labels:
      traefik.enable: true
      traefik.http.routers.jekyll.entryPoints: https    
    volumes:
      - .:/srv/jekyll

networks:
  marbles:
    driver: bridge
    external: true
